main: com.plushycat.mobby.Plugin
name: Mobby
version: 1.0.0
author: plushycat, LeMinaw
api-version: 1.20
description: Lightweight plugin to control the growth of some animals.

permissions:
  mobby.growth.*:
    description: Control all aspects of animal growth.
    default: op
    children:
      mobby.growth.stop: true
      mobby.growth.resume: true
  mobby.growth.stop:
    description: Allow stopping animal growth.
  mobby.growth.resume:
    description: Allow resuming animal growth.

  mobby.reload:
    description: Allow reloading the plugin configuration.
    default: op
  mobby.list:
    description: Allow listing tracked mobs
    default: op

commands:
  mobby:
    description: "Main command for Mobby (usage: /mobby <reload / list>)"
    usage: "/mobby <reload / list>"
